/**
 * @file CountWords.java
 * @author KUSHAGRA JAISWAL 
 * @date 2023-04-20
 * @copyright Copyright (c) 2023
 */

 /*
Develop and test a program to enter a maximum of five lines of text through keyboard terminating each line by a period
operator. The number of lines of text to be entered should be generated by a random number generator. Remove the period
symbol from each line and count the number of words in it excluding the articles and prepositions. The number of articles and
preposition present in the lines should also be counted and the number of words, articles and prepositions should be displayed
in the form of three different tables each showing the word/article/preposition and its frequency in the entire text lines. Count
the number of characters in the text entered. Convert each word except the articles and the prepositions into title case and
display the entire text. 
  */
package src.assignments.cat.set_A;
import java.util.Arrays;
import java.util.Scanner;
public class CountWords {

    public void splitWords(String str){
        //str.replaceAll("."," ");
        // String[] words = str.split(".");
        
        // for(int i = 0; i < words.length; i++){
        //     System.out.println(words[i]);
        // }
    }
    public static void main(String[] args) {
        System.out.println(Arrays.toString("one*two.three.four.five.".split("\\*")));
    }
}
